name: pcenv
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10.6
  - pip=22.2.2
  - pytorch-cuda=11.7
  - pytorch=1.13.0
  - torchvision=0.14.0
  - scikit-learn
  - pip:
    - tabulate>=0.8.9
    - matplotlib>=3.4.3
    - seaborn>=0.11.2
    - sklearn-sfa
